# Generated by Django 3.2.25 on 2025-02-15 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_usuario_cpf'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='main_user',
        ),
    ]
