# Generated by Django 3.2.25 on 2025-02-15 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_usuario_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table=None,
        ),
    ]
