# Generated by Django 3.2.25 on 2025-02-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_restaurante'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='horario_funcionamento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
