# Generated by Django 3.2.25 on 2025-02-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20250215_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='restaurantes/'),
        ),
    ]
