# Generated by Django 3.2.25 on 2025-02-16 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_restaurante_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurante',
            name='foto',
        ),
    ]
