# Generated by Django 3.2.25 on 2025-02-16 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_restaurante_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurante',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='horario_funcionamento',
        ),
    ]
